### ISSUE TITLE
change detection for multi language

### ISSUE THREAD

**Issue by ParadoxLeon** [ParadoxLeon/CS2-Translator#3]
#  untested

use  `if (!Regex.IsMatch(l, @"\s\s\[\w+\]") && !l.Contains("﹫"))` 

there a always to spaces before

**Comment by labaland** [comment]
Is this correct? :) 
Is it possible to send/make it send the translation in the chat? Thank you :) 

![Image](https://github.com/user-attachments/assets/6afeede8-d115-480e-a518-4415a3d39f18)

**Comment by ParadoxLeon** [comment]
> Is this correct? :) 
> Is it possible to send/make it send the translation in the chat? Thank you :) 
> 
> ![Image](https://github.com/user-attachments/assets/6afeede8-d115-480e-a518-4415a3d39f18)
> 

No the Multi Language is referring to detection in the logs.

It was possible to send translations to Chat but not anymore since valve disabled telnet.
